import {
  Pill,
  Users,
  PackagePlus,
  PackageMinus,
  BarChart3,
  Bell,
  Settings,
  LayoutDashboard,
  LogOut,
  Search,
  Menu,
  X,
  ChevronDown,
  ChevronRight,
  Plus,
  Edit,
  Trash2,
  Eye,
  EyeOff,
  Download,
  Upload,
  Calendar,
  Clock,
  AlertTriangle,
  AlertCircle,
  CheckCircle,
  XCircle,
  FileText,
  Filter,
  RefreshCw,
  ArrowUpDown,
  MoreHorizontal,
  Phone,
  Mail,
  User,
  Building2,
  Stethoscope,
  Activity,
  TrendingUp,
  TrendingDown,
  Package,
  ClipboardList,
  History,
  Tag,
  Info,
  Shield,
  Wifi,
  WifiOff,
} from "lucide-react"

export const Icons = {
  pill: Pill,
  users: Users,
  import: PackagePlus,
  export: PackageMinus,
  chart: BarChart3,
  bell: Bell,
  settings: Settings,
  dashboard: LayoutDashboard,
  logout: LogOut,
  search: Search,
  menu: Menu,
  close: X,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  plus: Plus,
  edit: Edit,
  delete: Trash2,
  view: Eye,
  eyeOff: EyeOff,
  download: Download,
  upload: Upload,
  calendar: Calendar,
  clock: Clock,
  warning: AlertTriangle,
  alert: AlertCircle,
  success: CheckCircle,
  error: XCircle,
  file: FileText,
  filter: Filter,
  refresh: RefreshCw,
  sort: ArrowUpDown,
  more: MoreHorizontal,
  phone: Phone,
  mail: Mail,
  user: User,
  hospital: Building2,
  doctor: Stethoscope,
  activity: Activity,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  package: Package,
  clipboard: ClipboardList,
  history: History,
  tag: Tag,
  info: Info,
  shield: Shield,
  wifi: Wifi,
  wifiOff: WifiOff,
}

export type IconName = keyof typeof Icons
